FEAT :: Teammate 페이지 개발 및 App.tsx에 추가
Bamdoliro/Bamdoliro pull request #4
Opened 2023-01-15 14:54 UTC by arkk200

## 📄 Summary
> 
그외
FEAT :: Context API 묶어주는 context 폴더 개발
FEAT :: Context API에 RadioContext로 RadioGroup, GenerationRadio 개발
FEAT :: Profile과 Profile을 묶는 ProfileGroup 개발
STYLE :: assets 폴더에 사진 추가
CHORE :: uuid 라이브러리 설치

<br>

## 🔨 Tasks
- 

<br>

## 🙋🏻 More

2023-01-19 12:54 UTC, gimhanul requested changes
멋있어용

2023-01-19 12:54 UTC, gimhanul commented on src/components/Teammate/index.tsx
> +  useEffect(() => console.log(radioNumber), [radioNumber]);
필요 없는 useEffect 삭제해주세염

2023-01-19 12:54 UTC, gimhanul commented on src/components/Teammate/index.tsx
> +        </ProfileGroup>
json file 만들어서 map 함수로 돌려주세염

2023-01-19 12:54 UTC, gimhanul commented on src/components/Teammate/index.tsx
> +        <GenerationRadio value={3}>3기</GenerationRadio>
이것도 마찬가지 Json file map 돌려주세염

2023-01-19 12:54 UTC, gimhanul commented on src/components/common/GenerationRadio/index.tsx
> +    const [id] = useState(uuidv4());
꼭 uuid 쓰는 이유가 있을까여?

2023-01-19 12:54 UTC, gimhanul commented on src/components/common/GenerationRadio/style.ts
> +    color: ${ ({ theme }) => theme.color.gray02 };
보니까 석진이 옆 PR에서 이거 바꿨던데 문의하고 머지해서 고쳐주세염

2023-01-19 12:54 UTC, gimhanul commented on src/components/common/Profile/index.tsx
> +}
type은 분리하는 게 좋을 듯

2023-01-25 15:01 UTC, gimhanul approved these changes

2023-01-25 15:03 UTC, gimhanul commented on src/components/common/Profile/index.tsx
> +}
이건 지금 보니까 또 props 타입이니까 파일 안에 있어야 되는 것 같기두 하네요

2023-01-25 15:13 UTC, SEOKKAMONI approved these changes

2023-01-25 15:13 UTC, merged